### ISSUE TITLE
AdviceFileAdvice use IFile / IPath just to convert them to a file

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#104]
org.eclipse.equinox.p2.publisher.AdviceFileAdvice requires IFile / I Path just to later on convert them to a file. It would be good to use File in the first place.

**Comment by merks** [comment]
That would be good for whom?  Why would it be good for them?  You're not planning something disruptive are you?  If you're using it, consider that others will be using it too and that changing it will definitely not be good for them after the fact.

**Comment by laeubi** [comment]
> That would be good for whom?

I don't need to convert File object to Ixxx just that the code converts it back to File

> You're not planning something disruptive are you?

I don't see anything disruptive here, just collecting some hacks in Tycho that should have been fixed upstreams long time ago...

**Comment by mickaelistria** [comment]
Adding a constructor that can work with plain File would seem proper and backward compatible.

> You're not planning something disruptive are you?

Disruption is welcome, it just need extra care to balance it with compatibility.

**Comment by laeubi** [comment]
> You haven't describe concretely what you plan to do

This is, because there is no plan :-)



> Adding a constructor that can work with plain File

Yes something like this, beside the constructor there is only `loadAdviceMap` which is private so it should not be an issue.

**Comment by merks** [comment]
I would prefer to see issues with a concrete plan of action or a clear statement of what is intended.  

In this case I don't think the second argument makes sense as a File because it represents a relative path.

![image](https://user-images.githubusercontent.com/208716/177603526-2422af98-83a3-484b-981f-c22d02ce7cac.png)

So I question where this is headed, but there is no point in asking a second time is there?

**Comment by laeubi** [comment]
I'm just not sure how to explain this e.g. take a look at:

https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/src/main/java/org/eclipse/tycho/p2/impl/publisher/ProductDependenciesAction.java

we construct Path elements from files and then P2 converts it back to some file, so my intention is that I can pass File(s), Strings, (java.Path) whatever in the first place without converting them first and the P2 converting them back....

**Comment by merks** [comment]
Okay, first it seems trivial and I think we've spent more time on this discussing than the issue is worth.  :-P

Also, here it's clear that the second argument is a relative path not a File.

https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/src/main/java/org/eclipse/tycho/p2/impl/publisher/ProductDependenciesAction.java#L90

And here we (I) do not have a File already and do not need one:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/tree/plugins/org.eclipse.oomph.targlets/src/org/eclipse/oomph/targlets/impl/FeatureGeneratorImpl.java#n348

If it were always a File, I would not have complained either, but I **don't want this code to be broken** such that I have to change the lower bound to only work with the latest IBuild.

So add an "overloaded" constructor if that feels super important to you, just don't break others.

**Comment by laeubi** [comment]
@merks just curious is it really a gib concern to have:

`new AdviceFileAdvice(..., ..., new File(location), p2.inf));`

versus

`new AdviceFileAdvice(..., ..., new Path(location), new Path("p2.inf"));`

> So add an "overloaded" constructor if that feels super important to you, just don't break others.

that's what most probably would be suitable here, and it not "super important" just something I noticed more than once and as you said seems a trivial fix, so I have not expsected that big concerns here :-)

**Comment by merks** [comment]
@laeubi Again, I **don't want this code to be broken** such that I have to change the lower bound to only work with the latest IBuild.   If you want something, add it, but please **do not** remove/change/break what I am (and who knows how many others are) using.  What I want is just as important as what you want.  Surely it's not necessary to break this "API" and surely it's not necessary to flog the horse further.

**Comment by laeubi** [comment]
Closing this as not being relevant anymore (for me) as it seems more profitable to get rid of outdated P2 technology in Tycho and moving on to more modern and flexible approaches:
- https://github.com/eclipse-tycho/tycho/issues/2019
