### ISSUE TITLE
Use a tree datastructure in the Slicer to record how units where considdered

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#139]
Currently the `Slicer` internally uses a flat list / set to record considered units. While this is sufficient if one only tries to compute items to install, it makes certain operations very hard for example:

- I like to know the dependency chain why a certain IU was considered, e.g. A is a root IU and X is selected, I like to find out why X is chosen (assuming it is not a direct requirement of A), e.g. in the for A requires B requires C requires X
- I like to only fetch a subtree, for example A and all direct dependencies
- I like to calculate the fan out/in of a dependency
- ...

To archive this, the `Slicer` should internal maintain a tree whose roots are the root IUs, the nodes are IUs and that are connected by a requirement and two ways to access this:

1. a `Slicer#filterTree` method, that can remove nodes after the inital calculation
2. a `IQueryableTree` that extends `IQueryable`and allows to query for subtrees, e.g. by specify a IU or traverse its direct childs

This would be very useful e.g. for Tycho when it assembles a repository, when it display the dependency tree and when it compute the inter-project relations to find a suitable build order.

**Comment by mickaelistria** [comment]
I'm not sure that would be so easy: the result of a slicing operation takes all constraints together at once, so resolving a subtree can easily result in different IUs than resolving multiple roots. Some constraint in an unrelated requirement from a different subtree will interfere with the result.
We basically don't have a tree structure because all constraints are considered equals and do interact together.
So I don't think the slicer is the right place; but maybe some extra tools (that wouldn't even require p2 but could run with the OSGi resolver) could be implemented to analysis a planner/slicer resolution.

**Comment by laeubi** [comment]
I really only want to represent what the slicer does while traversing the requirements, for sure you cant _resolve_ sub-trees, but you can `traverse` them.

The Slicer work as follows:

1. Init the set with all root IUs (--> will be the roots of the tree)
2. remove one IU from that set an query for a requirement
3. for each accepted requirement, find any matching IU und add it to the set (if it was not processed before)
4. iterate until the set is empty

this is similar to https://en.wikipedia.org/wiki/Breadth-first_search and could be represented as a tree with multiple roots. Of course you will never get a "perfect" tree but for the outlined use-cases it is enough, or you can simply use a single root IU if you want a full tree.

**Comment by laeubi** [comment]
Closing this as not being relevant anymore (for me) as it seems more profitable to get rid of outdated P2 technology in Tycho and moving on to more modern and flexible approaches:
- https://github.com/eclipse-tycho/tycho/issues/2019
