### ISSUE TITLE
Use import-package instead of require bundle for the P2 API to allow better integration

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#22]
In https://github.com/eclipse-equinox/p2/commit/d7e1f8c0ce622c316c8f0f48f28fce364ea745dd @mickaelistria provided a nice workaround to instruct P2 forcing to use a certain bundle, so I think it is time to get rid completely of require bundle in p2 (that means, replace any occurrence of require-bundle by appropriate import package, with a version range if possible).

This will allow us to be even more flexible when using p2 in other context and is even recommended by the OSGi spec: https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#i3198951

**Comment by merks** [comment]
It seems impractical to suggest to get rid of something used by almost every bundle in existence.   It's not even clear what "getting rid of means", but if if means removing support for it, that would first involve deprecation for some period of time...

There are roughly 478 bundles in my SDK workspace. and almost all of them use Require-Bundle while almost none of them version their packages.  Because very few bundles version their exported packages, replacing a Require-Bundle with a version range with an Import-Package without a version range is not a fully functional replacement.

So I think prerequisites are as follows:

1. get the community to agree that we should "get rid of this"
2. get the platform do this for all its bundles
3. get all the platform's bundles to version their packages.  
4. ensure that API tooling supports checking package versions, implementing that if not already there

Then we will have to live with even more frequent build failures from missing but necessary package version changes in addition to the missing but necessary bundle version changes.

It seems unlikely to get beyond the steps above to get the point where this issue is relevant to p2.

**Comment by laeubi** [comment]
> It seems impractical to suggest to get rid of something used by almost every bundle in existence

That's simply wrong ... just because *platform* is used to require bundle it is invalid to state "almost every bundle" is doing this, I assume you have not checked [all 21.073 bundles]( https://search.maven.org/search?q=p:bundle) on central, not counting the ones that simply use "jar" packaging....

> Then we will have to live with even more frequent build failures from missing but necessary package version changes in addition to the missing but necessary bundle version changes.

Can you prove this?

> So I think prerequisites are as follows:

This has nothing to do with this topic.

> Because very few bundles version their exported packages, replacing a Require-Bundle with a version range with an Import-Package without a version range is not a fully functional replacement.

Just because others doing bad things do not mean P2 can't do better, beside that I see a lot of versioned packages in platform bundles.
