### ISSUE TITLE
Computing 15 alternatives for an update in p2

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/p2#253]
If I update my SDK I alway have to wait for p2 to compute this 15 alternatives.

The surprising alternative which is picked is the update. 

Situation:

![image](https://user-images.githubusercontent.com/139910/232730095-e26d0d07-6d99-4b52-9227-4069ef03c132.png)

Now p2 starts doing its "deeping learning algorithm" to find the solution for the update problem.

![image](https://user-images.githubusercontent.com/139910/232730148-e9dc363f-f46b-4a43-b495-b9f667af3a49.png)

And the solution is (always) to try an update.

![image](https://user-images.githubusercontent.com/139910/232730454-f25b5ecb-3de8-4587-a85c-0b8eb2d39653.png)

I never looked at the coding but:

- Why is it always 15 alternatives?
- Why not just try to update and calculate alternatives if this fails?

**Comment by vogella** [comment]
cc @merks and @laeubi as both worked with p2 in the past months.

**Comment by merks** [comment]
Given the original designers of the framework are AWOL, answering this will involve significant forensic analysis, and of course detailed steps to reproduce the problem.  I really don't have time for such analysis., so this issue is likely to linger until it is auto-closed.

**Comment by mickaelistria** [comment]
Can you please show the orginal error (selecting this option in the dialog)?

> Why not just try to update and calculate alternatives if this fails?

That's what is happening, the issue here is not that there is no error, but instead that the error that triggered computing alternatives did not surface. I suspect it's just 1 installable unit that was skipped.

> Why is it always 15 alternatives?

Finding a viable plan is a NP problem (SAT family); 15 is probably a good heuristic of how deep to go to compute viable solutions in most cases for p2. @danielleberre may recall the rationale for 15.

**Comment by vogella** [comment]
> Can you please show the orginal error (selecting this option in the dialog)?

I did not see an error.

**Comment by vogella** [comment]
> Given the original designers of the framework are AWOL, answering this will involve significant forensic analysis, and of course detailed steps to reproduce the problem. I really don't have time for such analysis., so this issue is likely to linger until it is auto-closed.

A great feature (no irony, I really like it) We should add auto-close to our other repos too, it makes no sense to have outdated issues lying around on which no one plans to work.

Still good to open such issues, as the next time you may see the "computing 15 alternatives" you may also think "how stupid is this" and if you stumble over the code you may remember this issue.

**Comment by laeubi** [comment]
> A great feature (no irony, I really like it) 

And others (including me) don't like it, I haven't seen any of the promised values yet here, beside that I'm getting useless mails and need to remove labels if my issues are affected (and still not solved.

Beside that, it might be 15 for you but that's not fixed, it could be 2, 3, 5, ...any number...

> I did not see an error.

You should select the last bullet point.

**Comment by merks** [comment]
Note that one choice is show original error.  You have to choose that to see the original error and I think that's with @mickaelistria  wants to see.

**Comment by laeubi** [comment]
> I think that's with @mickaelistria wants to see.

Be careful I recently learned if we see error we learn to ignore them (because errors are annoying!), so that was probably the intention here to **not** see it ;-)

**Comment by vogella** [comment]
> Beside that, it might be 15 for you but that's not fixed, it could be 2, 3, 5, ...any number...

IIRC every time I have seen this message over the last years, it was 15.  

> You should select the last bullet point.

Silly me, here it is:

````
Your original request has been modified.
  "Eclipse Project SDK" is already installed, so an update will be performed instead.
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Project SDK 4.28.0.v20230417-2128 (org.eclipse.sdk.feature.group 4.28.0.v20230417-2128)
  Software currently installed: Eclipse SDK 4.28.0.I20230403-1800 (org.eclipse.sdk.ide 4.28.0.I20230403-1800)
  Only one of the following can be installed at once: 
    Eclipse Project SDK 4.28.0.v20230417-2128 (org.eclipse.sdk.feature.jar 4.28.0.v20230417-2128)
    Eclipse Project SDK 4.28.0.v20230403-2036 (org.eclipse.sdk.feature.jar 4.28.0.v20230403-2036)
  Cannot satisfy dependency:
    From: Eclipse Project SDK 4.28.0.v20230403-2036 (org.eclipse.sdk.feature.group 4.28.0.v20230403-2036)
    To: org.eclipse.equinox.p2.iu; org.eclipse.sdk.feature.jar [4.28.0.v20230403-2036,4.28.0.v20230403-2036]
  Cannot satisfy dependency:
    From: Eclipse Project SDK 4.28.0.v20230417-2128 (org.eclipse.sdk.feature.group 4.28.0.v20230417-2128)
    To: org.eclipse.equinox.p2.iu; org.eclipse.sdk.feature.jar [4.28.0.v20230417-2128,4.28.0.v20230417-2128]
  Cannot satisfy dependency:
    From: Eclipse SDK 4.28.0.I20230403-1800 (org.eclipse.sdk.ide 4.28.0.I20230403-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.sdk.feature.group [4.28.0.v20230403-2036,4.28.0.v20230403-2036]

````

15 alternatives calculated for this challenging scenario of updating one SDK build to the next one.

**Comment by laeubi** [comment]
> IIRC every time I have seen this message over the last years, it was 15.

Probably because you always perform the same thing, but at least I have already seem 2 or 5 alternatives computed in other cases. I haven't checked this in detail, but P2 just tries to per-mutate your request, e.g. in this case it replaces the **install** of in IU by the **update** of the IU, possible other ways I'have seen is **unistalling** some conflicting things. or **skipping** the install of a new feature.

> Silly me, here it is:

Is it possible that you try to *install* the SDK instead of *updating* it? If I remember corectly adding the Ibuild repo to your update sites is enough and then you simply can perform "Check for Updates"

**Comment by iloveeclipse** [comment]
> I recently learned if we see error we learn to ignore them (because errors are annoying!),

You unfortunately learned the wrong thing. 
Please check at https://en.wikipedia.org/wiki/Broken_windows_theory to understand what was meant.

**Comment by laeubi** [comment]
> Please check at https://en.wikipedia.org/wiki/Broken_windows_theory to understand what was meant.

I already understood that platform now is the visible signs of [crime](https://en.wikipedia.org/wiki/Crime), [anti-social behavior](https://en.wikipedia.org/wiki/Anti-social_behavior) and [civil disorder](https://en.wikipedia.org/wiki/Civil_disorder) [...] that encourages further crime and disorder, including serious crimes.

**Comment by danielleberre** [comment]
@mickaelistria The remediation was implemented by Pascal Rapicault. I do not know the details of the procedure.

@vogella The issue is that one of the dependency cannot be satisfied, probably because you do not have the v20230417-2128 version for that dependency in your repository.

**Comment by merks** [comment]
There are 2^4 combinations of the 4 bits that it tries with false/true settings:

https://github.com/eclipse-equinox/p2/blob/2f11750cb8b4beeef3be6a03dd807466771b8102/bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/RemedyConfig.java#L51-L80

What you appear to show is a attempt to install something which it turns out is already installed so it's going to need to update something(s), rather than just install your one thing, and in this case not just update that one thing, but several things.  It might even proposing having to uninstall something else in other scenarios.  So it is trying to "just update" things, i.e., that is one of the alternatives.

If you want to just update, then you can just check for updates instead which will find updates and just install them without remediation.

I think that answers the questions.
