### ISSUE TITLE
A Context Menu and TrustAuthorityDialog block each other

### ISSUE THREAD

**Issue by DenisUngemach** [eclipse-equinox/p2#299]
Hello, 

at the installation of new software, an open context menu can block the TrustAuthorityDialog, which comes up if the software comes from a not trusted source.

Reproduce:

-> Open for example a text file, where you can open a context menu.

-> "Install New Software..." for example from this not trusted update site:
     https://spotbugs.github.io/eclipse-latest

-> Install also multiple other software from other update sites. This is just necessary to create a delay until the TrustAuthorityDialog comes up.

Finish the wizard, so the software installation starts.

Now open the context menu of the text editor.
Some seconds later dependent on the size of your software installation, the TrustAuthorityDialog comes up.

Now the context menu blocks the TrustAuthorityDialog and this blocks the eclipse UI.

As a workaround, you can just press the Windows key in order to close the context menu, then everything is fine.

One of the reasons might be that the TrustAuthorityDialog is SWT.Modeless. 

Usually  jface dialogs wait until the context menu is closed. I don't know what happens here.

Hope you can find the reason.

My OS: Windows 11.
eclipse 4.29, but reproducible also with other eclipse version.

![EclipseContextMenuBlocksTrustAuthorityDialog](https://github.com/eclipse-equinox/p2/assets/108277444/81b2eda1-59ce-4ea5-aa00-528ba11c9089)

**Comment by DenisUngemach** [comment]
It seems this won't be fixed...

**Comment by merks** [comment]
Yes, probably not.  The problem is that one has no idea what the UI is doing when the dialog is opened.  Similarly for password prompts or other prompts that are launched from a background job.  There could be other dialogs open and one even has to be careful which parent shell is used so that one modal dialog does end up under another modal dialog.  I'm not even sure if there is a way to know there is a menu open and to dismiss it.  There are certainly many other fish to fry and only limited time for any of them...
