### ISSUE TITLE
Support names for Updates repositories in product definition

### ISSUE THREAD

**Issue by HannesWell** [eclipse-equinox/p2#345]
It should be possible to specify a name for an Repository referenced in the Updates configuration section of a Product.

In P2 this requires a consideration of a name attribute in org.eclipse.equinox.internal.p2.publisher.eclipse.ProductFile,processRepositoryInformation() and when the read repositories are processed.
In PDE the `UpdatesSection` and `IRepositoryInfo` need to be enhanced to also support adding a name attribute.

@jcompagner since you raised the issue, are you interested in working on this?

### Discussed in https://github.com/eclipse-equinox/p2/discussions/342

<div type='discussions-op-text'>

<sup>Originally posted by **jcompagner** October  2, 2023</sup>
Hi,

not sure where the product file belongs to that makes the product (is this platform or rcp? or p2?)

So i asked the question here, in the product file (editor) you can define your repositories where this product builds from (or updates from)

Problem is the name is not asked for, and then when you install it, in the preferences it is displayed very weird, because you have a lot without a name. The name seems kind of a bit mandatory (also in the p2.inf where i now place it)

Is there a reason for that? i tries to just adjust the product xml file by adding "name=xxx" or "displayname=xxx" but that isn't picked up.

</div>

**Comment by HannesWell** [comment]
@jcompagner are you interested in working on this? If not I'll take care of this.

**Comment by jcompagner** [comment]
yes i can have a look
But a bit busy, and next week i will be at Eclipse Con in Ludwigsburg ...

**Comment by ajohnson1** [comment]
I did not get the update section of the product definition to work with Eclipse Memory Analyzer.
https://git.eclipse.org/c/mat/org.eclipse.mat.git/tree/org.eclipse.mat.product/mat.product

Instead I had to use a p2.inf file:
https://git.eclipse.org/c/mat/org.eclipse.mat.git/tree/org.eclipse.mat.product/mat-2023-12.p2.inf

This is with a Tycho/Maven build.

**Comment by jcompagner** [comment]
> Great. I'll be there too, so maybe we can have a chat about this topic. :)

we can have a meet up then in the coming few days..  to see each other face to face is always nice.

**Comment by HannesWell** [comment]
@jcompagner can you tell already If/when you can look into the PDE-Editor support for this feature?

**Comment by jcompagner** [comment]
i will have a look hopefully today,

But first i need to look at another PDE issue that suddenly pops up today
our main target file has "com.sun.jna" showing up under the content
But if we say "export" then the local dir target that is created doesn't have that jar for some reason..

And this i a problem, because my whole team works like that, we always export to a local dir "workspace/launch_target" and use that local target as our main target for developement
This is because PDE now and then always wants to connnect to remote stuff (even if set active target platform is not called for a long time) and if it then fails, you can't develop anymore because it doesn't resolve the target. which is really annoying

So we worked around this by always creating a local target from our main target.. And use that one, then the target never just invalidates because of some connection problems.
But suddenly now the export target doesn't work for some reason it doesn't generate the whole thing..

**Comment by jcompagner** [comment]
https://github.com/eclipse-pde/eclipse.pde/pull/824

**Comment by HannesWell** [comment]
This is now completed and supported in p2 and PDE:
- https://github.com/eclipse-equinox/p2/pull/353
- https://github.com/eclipse-pde/eclipse.pde/pull/824

Thanks @jcompagner again for your help on this.

**Comment by HannesWell** [comment]
Just created a new and noteworthy entry for this new feature:
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/78
