### ISSUE TITLE
feature.feature in feature ID intentional?

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/p2#553]
While updating a super old tutorial of mine for integrating p2 into Eclipse RCP (https://www.vogella.com/tutorials/EclipseP2Update/article.html) , I noticed that p2 uses **feature.feature.group** as as suffix while platform and sdk uses **.feature.group.** Is this intentionally or just a fallout of some old configuration? 

If not intentional can we change it or would it break the world?

````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/releases/2024-09"/>
			<unit id="org.eclipse.equinox.sdk.feature.group" version="3.23.1400.v20240820-0604"/>
			<unit id="org.eclipse.platform.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.equinox.p2.core.feature.feature.group" version="1.7.300.v20240801-1024"/>
			<unit id="org.eclipse.equinox.p2.rcp.feature.feature.group" version="1.4.2500.v20240801-1024"/>
		</location>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/justj/jres/21/updates/release/latest"/>
			<unit id="org.eclipse.justj.openjdk.hotspot.jre.minimal.feature.group" version="21.0.4.v20240802-1551"/>
		</location>
		<location includeDependencyDepth="infinite" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>com.google.code.gson</groupId>
					<artifactId>gson</artifactId>
					<version>2.8.6</version>
					<type>jar</type>
				</dependency>
			</dependencies>
		</location>
	</locations>
</target>

````

**Comment by laeubi** [comment]
>  I noticed that p2 uses feature.feature.group

P2 uses `<name of feature>.feature` (as many others as well to prevent name clash with bundle ids, e.g.

`org.eclipse.p2.core` (the bundle) versus `org.eclipse.p2.core.feature` (the feature containing all core p2 components).

In **the repository format** every feature gets translated into two IUs
- feature itself (--> `<ID>.feature.group`)
- the feature jar (--> `<ID>.feature.jar`)

The PDE uses Unit-IDs to address features and bundles equally (so there is no difference in the type possible), that's why one sees then `org.eclipse.equinox.p2.core.feature.feature.group` but that's nothing shown in the UI (where only the ID is shown) so I don't think its worth to change anything here to make the display in a raw text format "feel better".

**Comment by vogella** [comment]
Makes sense, thanks @laeubi
