### ISSUE TITLE
Classpath problems in org.eclipse.equinox.p2.touchpoint.eclipse

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/p2#58]
This morning after pulling all the latest sources, the org.eclipse.equinox.p2.touchpoint.eclipse has this error

```
The project was not built since its build path is incomplete. Cannot find the class file for org.eclipse.core.runtime.preferences.IEclipsePreferences. Fix the build path then try building this project	org.eclipse.equinox.p2.touchpoint.eclipse		Unknown	Java Problem
The type org.eclipse.core.runtime.preferences.IEclipsePreferences cannot be resolved. It is indirectly referenced from required .class files	RepositoryAction.java	/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/touchpoint/eclipse/actions	line 257	Java Problem
```

This can be resolved by adding a package import
```
 org.eclipse.core.runtime.preferences;version="[3.0.0,4.0.0)",
```

**Comment by merks** [comment]
@HannesWell  Any idea why this new issue might have cropped up?

**Comment by laeubi** [comment]
@merks see https://bugs.eclipse.org/bugs/show_bug.cgi?id=328057

**Comment by merks** [comment]
Yes, I understand it's an age old problem, but why was not a problem yesterday but it is a problem today.  Also, this isn't just some internal dependency as suggested in that bug, it's in the API that's being used by calling org.eclipse.equinox.p2.engine.ProfileScope.getNode(String) which returns IEclipsePreferences, so this project is directly using the  API about which the  error complains.

**Comment by laeubi** [comment]
> Yes, I understand it's an age old problem, but why was not a problem yesterday but it is a problem today.

I think it could be related to @HannesWell  changes as you correctly guessed. I just wanted to remind of that ticket that we better find a solution for the root cause of the message than adding more imports for mostly unrelated changed.

> Also, this isn't just some internal dependency as suggested in that bug, it's in the API that's being used by calling

I don't remember the bug where I posted a reproducer, but the problem is not for internal API only.

> the API that's being used by calling org.eclipse.equinox.p2.engine.ProfileScope.getNode(String) which returns IEclipsePreferences, so this project is directly using the API about which the error complains.

Well.. not really `getNode` is part of the OSGI `Preferences` that `IEclipsePreferences` extends, so from java POV you are calling not `IEclipsePreferences` ...

**Comment by merks** [comment]
Well, it seems like it was self-inflicted because I was pulling from my fork's master branch which is out of date.

I've previously switched to a workflow where I create a separate remote for my fork and always switch back to master which uses origin which points a the clone to avoid such problems but didn't notice I'd messed up the p2 repo's origin to point at my fork.

**Comment by HannesWell** [comment]
> @HannesWell Any idea why this new issue might have cropped up?

This is due to https://github.com/eclipse-equinox/equinox.bundles/pull/39 and the problem you described should already be fixed by https://github.com/eclipse-equinox/p2/pull/57.
The problem is that the package was effectively moved to another bundle and although this should cause such failures because the resolve should simply take package from the other bundle.
But obviously the resolver makes also the other packages of that bundle available (at least for these indirect requirements).

> > Yes, I understand it's an age old problem, but why was not a problem yesterday but it is a problem today.
> 
> I think it could be related to @HannesWell changes as you correctly guessed. I just wanted to remind of that ticket that we better find a solution for the root cause of the message than adding more imports for mostly unrelated changed.
> 

Yes definitely we should fix the root cause! But what I don't understand with the 'missing indirect requiremtens' is this something the Java-compiler really needs or is this some Eclipse specialty?

> > Also, this isn't just some internal dependency as suggested in that bug, it's in the API that's being used by calling
> 
> I don't remember the bug where I posted a reproducer, but the problem is not for internal API only.

Probably here: https://github.com/eclipse-equinox/equinox.bundles/pull/31#issuecomment-1112864831

**Comment by laeubi** [comment]
> But what I don't understand with the 'missing indirect requiremtens' is this something the Java-compiler really needs or is this some Eclipse specialty?

Ii is EJC (Eclipse Java Compiler), probably PDE (configuring it) probably some Eclipse Specialty as well :-)
