### ISSUE TITLE
default implement Transport.download(URI, OutputStream, IProgressMonitor)

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#7]
`org.eclipse.equinox.internal.p2.repository.Transport.download(URI, OutputStream, IProgressMonitor)` actually handles some caller responsibility instead of adding real value in terms of implementation.

P2 should provide a default implementation here to lower the burden of implementing a custom transport.

**Comment by mickaelistria** [comment]
Can you please provide details about such caller responsibility? Couldn't we extract an abstract class (eg `TransportWithCacheAndRetries`) that provides the "dirty" parts and let extenders only focus purely on the transfer? So one could implement a new transfer just by implementing eg the `stream(...)` method.

**Comment by laeubi** [comment]
> So one could implement a new transfer just by implementing eg the `stream(...)` method.

Yes this would be perfect. Sad enough I noticed that transport has some more responsibilities so it might be not *that* easy to accomplish...

**Comment by merks** [comment]
I really wish I understood the bigger picture here (the final goal or at least a sketch of the final goal) rather than these snips and pieces of proposed changes without context.   I.e., here we talk about a default implementation in the abstract class, but why does that matter when RepositoryTransport is the only implementation of it in p2 itself?

**Comment by mickaelistria** [comment]
One of the goals of such change is to progressively allow abandoning requirement on ECF in p2 to use the JVM HTTP client capabilities directly.

**Comment by laeubi** [comment]
Actually one could ask why not simply use `URL.openStream()`? The only thing I see to far ECF offers is a way to pause a download... I must confess I've never seen such an opportunity in the P2 UI do I simply missed something here?

**Comment by vogella** [comment]
@laeubi HTTP client has a nice API. Can you push a WIP PR for your idea with URL.openStream(), if desired I can push a comparison RP for HttpClient and we compare and pick the better looking one?

**Comment by laeubi** [comment]
@vogella I really don't care about "nicer" API, the point is that P2 does not use exclusively http but any URI.
Currently P2 checks if its a file, the do some special handling, if not query ECF what does some special handling if its http (usinng Commons HTTP5 client) and otherwise URL.OpenStream(). Al this in the end results in an InputStream produced.

As every URI that could be converted into an URL (that includes file, http, and any URLHandler registered) can be opened as a stream, one might argue that we could simply open a stream directly from the URL.

**Comment by mickaelistria** [comment]
> As every URI that could be converted into an URL (that includes file, http, and any URLHandler registered) can be opened as a stream, one might argue that we could simply open a stream directly from the URL.

Great realization! +1000!

**Comment by merks** [comment]
I wonder how proxy settings, proxy authentication, and private repositories requiring authentication will work?  I think one should not assume that there is endless gratuitous complexity in the existing implementation.   Or to put it differently, do you really think the original developers never noticed URL.openStream is quite simple?   Are you sure no one has extended ECF in order extend p2?  So many assumptions...

**Comment by laeubi** [comment]
> I wonder how proxy settings, proxy authentication

https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection(java.net.Proxy)

> and private repositories requiring authentication

https://docs.oracle.com/javase/9/docs/api/java/net/HttpURLConnection.html#setAuthenticator-java.net.Authenticator-

> will work?

> think one should not assume that there is endless gratuitous complexity in the existing implementation.

Given that we get not even basic http caching the complexity is quite huge. Even though one should also not assume that no one else was able to handle a certain task just because it was not invented here.

> Are you sure no one has extended ECF in order extend p2?

Don't know is ECF a perquisite for P2?

**Comment by mickaelistria** [comment]
> Don't know is ECF a perquisite for P2?

No, p2 has no strong dependency on ECF. ECF is currently used in the only working transport available, but if we can achieve the same with standard Java (I think plain Java can do at least the same or better given how JVM APIs have constantly evolved for a long time from many contributors and many consumers; while ECF is a more intimist project) then there is no reason for p2 to stick only to ECF by default.
Java URL API has extensibility to support any protocol, the HTTP support has proxy and authentication capability... I don't know what are the selling point of ECF over Java URL/HTTP API that justify using it, except "it's here and it works" as looking forward it's not certain we can rely on this assumption for too long.
I personally find more profitable to spend 1 week to write a transport based on standard Java URL/HTTP than to spend 1 day fixing some ECF-based code.

Of course, adding a new transport doesn't mean we need to remove the ECF transport as long as some people are maintaining it. Both can coexist and consumers can pick one or the other as they prefer.

**Comment by akurtakov** [comment]
> > Don't know is ECF a perquisite for P2?
> 
> No, p2 has no strong dependency on ECF. ECF is currently used in the only working transport available, but if we can achieve the same with standard Java (I think plain Java can do at least the same or better given how JVM APIs have constantly evolved for a long time from many contributors and many consumers; while ECF is a more intimist project) then there is no reason for p2 to stick only to ECF by default. Java URL API has extensibility to support any protocol, the HTTP support has proxy and authentication capability... I don't know what are the selling point of ECF over Java URL/HTTP API that justify using it, except "it's here and it works" as looking forward it's not certain we can rely on this assumption for too long. I personally find more profitable to spend 1 week to write a transport based on standard Java URL/HTTP than to spend 1 day fixing some ECF-based code.

Oh, I can assure you that ECF costed Sravan, Mat and me way more in the last couple of years. We are probably speaking of at least a month. And all the parts that p2 uses are or no interest for Scott so every CVE in httpclient, switch to newer httpclient, releng fixes and etc. is practically done by us. Aka we don't gain anything from using ECF, it's just doing the work at another place with more limitations.

**Comment by laeubi** [comment]
> Of course, adding a new transport doesn't mean we need to remove the ECF transport as long as some people are maintaining it. Both can coexist and consumers can pick one or the other as they prefer.

What has confused me (and probably the ECF people as well as I'm opening confusing bugs against them) is that the P2-ECF code is actually at P2 while I always blame ECF for any errors where I read "ecf" in the error :-D

So probably it would be the best to fisrt move ECF transport to ECF project (note that currently there are some hard references to ECF in P2!)... then we can be sure that

1. The transport is pluggable
2. It is clear that the transport has to be maintained in the context of ECF

**Comment by akurtakov** [comment]
> > Of course, adding a new transport doesn't mean we need to remove the ECF transport as long as some people are maintaining it. Both can coexist and consumers can pick one or the other as they prefer.
> 
> What has confused me (and probably the ECF people as well as I'm opening confusing bugs against them) is that the P2-ECF code is actually at P2 while I always blame ECF for any errors where I read "ecf" in the error :-D
> 
> So probably it would be the best to fisrt move ECF transport to ECF project (note that currently there are some hard references to ECF in P2!)

The other way around move ECF code used by p2 only to p2 is probably more likely. @scottslewis mentioned multiple times he would be in favor of that IIRC.

> ... then we can be sure that
> 
>     1. The transport is pluggable
> 
>     2. It is clear that the transport has to be maintained in the context of ECF

**Comment by laeubi** [comment]
I think this would effectively move most parts of ECF to P2 (or more @eclipse-equinox ...). I'm just not sure how the responsibilities are regarding the ECF project, about its context and future plans.

**Comment by scottslewis** [comment]
Howdy.  For those that don't know, I'm the project lead for ECF.   

For context:   I defined and implemented ECF filetransfer before used by p2.   ECF filetransfer API + impls was defined to provide a transport-impl-independent filetransfer API.   When p2 implemented their file transfer with ECF filetransfer API...with http/https of course...they implemented ECFTransport (p2 class) to create yet another layer of pluggability.   I personally didn't work with that code (I can't even remember who was responsible for it), and wasn't consulted on it's design or impl.   If I were, I probably would have suggested either other ways to do what it does (e.g. mirror handling/retry logic, couple of other things as I recall), or perhaps suggested/provided changes to ECF to support specific things (like http caching...which...many years ago I suggested creating/adding a caching API + impl to ECF filetransfer but never got any support for it).

Now, however, ECF project's interest in filetransfer specifically has dropped to near zero, as ECF is mostly focusing on it's standards compliant impl of the Remote Services/RSA part of OSGi specification.  At least that's where my attention is, except when the platform wants/needs something wrt ECF filetransfer (the main thing being recently updates to httpclient impl as httpclient changes/fixes come out).

I (Scott) am the only committer that supports ECF filetransfer any longer.  There were several committers that were doing active ECF filetransfer development supporting Platform's needs (e.g. proxy support, etc) years ago, but given we receive no support for this work from anyone (commercial members, EF, no one)...and I have plenty of other work requirements on me to keep me busy...I'm only able to do the barest minimum or supporting Platform/p2's ongoing needs.

Under other circumstances I would be happy to do more (new features such as caching, moving down some of p2's ECFTransport API into ECF, possibly other download/filetransfer features), but as I've said before that's just not possible without visible means of support.   I'm happy to help others if they want to take things on (as have akurtatov, etc), but I'm very very hesitant to commit to *either* moving ECFTransport into ECF (as this would likely mean more unpaid work for me) or moving parts of ECF (e.g. filetransfer) into Equinox...as that would also likely require more work from me...since I believe I'm the only person with sufficient knowledge of the existing codebase to maintain it effectively (at least right now).   

Also...FWIW...there are other consumers of ECF filetransfer (other than Eclipse Platform) that I have to at least consider...this makes me more hesitant to move ECF filetransfer to p2.

BTW I would not be against having someone implement/replace ECFTransport with something other than ECF...but I'm not going to do that myself.   Also...supporting an app like Eclipse that's used in such a variety of old and new network environments (proxies, firewalls, mirrors, oh my, etc., etc) is an intense pain which although better supported by projects like httpclient are not (IMHO) up to trivially replacing ECFTransport without possible regression.

But...as I said...at this point me/ECF are not focused on developing the filetransfer bundles/features since it's already an unsustainable drain on my resources...and it's not the active part of ECF...excepting the ongoing maintenance needs primarily from Platform.

**Comment by scottslewis** [comment]
@laeubi RE: feasibility of splitting the ecf-transfer component from ECF...I think you mean splitting the ECF Filetransfer component from ECF?   If that's what you are asking:   ECF has a filetransfer API (represented by bundle:  org.eclipse.ecf.filetransfer) and implementations of this API,,,referred to as providers (currently httpclient 5).   All of the providers depend (of course) on the filetransfer API.  The filetransfer API depends upon two ECF 'core' bundles:  org.eclipse.ecf and org.eclipse.ecf.identity.   Other parts of ECF (e.g. remote services) depend upon these two core bundles, but generally do not depend directly on the filetransfer API.

The good news is that these 'core' bundles change only rarely these days (the API bundles also are not changing much these days as well).

So it's technicall feasible that ECF filetransfer (API + provider impls) could be moved into some other project (platform, equinox),  but I don't think that could work for the core bundles.

**Comment by merks** [comment]
Oomph uses these things from ECF directly:

![image](https://user-images.githubusercontent.com/208716/164173507-b15fc747-e6bf-4b81-af01-a3646f9d7e65.png)

**Comment by scottslewis** [comment]
> 

Hi @laeubi .   In my previous response I think I may have misunderstood your question:   Can you tell if it is even feasible to split the ecf-transport component from ECF? Does ECF do not require this?

Unless something has changed, the ecf-transport component is currently not a part of ECF at all (so yes it can be separated from ECF...and it already is separated from ECF).  I believe it's in the p2 namespace:  org.eclipse.equinox.p2.transport.ecf.   If that was what you were asking, then 'yes' :).  Sorry if I interpreted incorrectly above your question as about the structure of ECF wrt abstractions (API vs. impl and filetransfer vs. core).

I'm not sure when/who p2 ecf filetransfer was moved into a separate bundle from the rest of p2, but it was...as I recall because someone on the p2 team wanted to provide their own transport...and didn't realize that it wasn't simple to support the stuff ECF filetransfer currently supports (e.g. proxy config, async/callback/threading/jobs... independent of http impl (i.e. apache httpclient version) etc.

Anyway, as Ed shows in his previous comment, It is quite possible to use ECF filetransfer directly...as oomph does this already.   I believe there are other consumers that do this also.
