### ISSUE TITLE
Pass response headers in DownloadStatus

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#8]
Currently DownloadStatus returns the last modified and the speed. For gathering more context, it would be usefull to have a `Map<String, String[]>` containing the (http) headers.

What I'm wondering about: Are there actually any non-http repositories used by someone? Maybe some ftp mirrors?

**Comment by merks** [comment]
Of course there are very often file: repositories.   Also even zip:http: repositories in which case the "header" information would be about the overall .zip and not about the individual files in that zip.  And in the end, whatever extensible schemes are supported by the JRE are supported, so even platform:/resource works within an IDE; I tried it just now.

**Comment by laeubi** [comment]
> Of course there are very often file: repositories

I'm more interested in remote items, as file is already special handled by P2

> Also even zip:http: repositories

It seems the P2 in those cases downloads everything multiple times, in any case one could assume that if the zip not change the content won't change.

**Comment by merks** [comment]
Nevertheless, any URI scheme should work (and this is pluggable) so you should not make assumptions that only http/https is remote.  So just reading the title (your stated goal) I think, http header information will not generally be available.  So that makes me wonder the context for how that would be used as I see various somewhat-related issues being opened...
